version: "2"
services:
    www:
        build: .
        image: cementerio:1
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.6
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: cemenweb_dbweb
            MYSQL_USER: cemenweb_webusua
            MYSQL_PASSWORD: wRmWxTGl1L4f
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini/uploads.ini
        environment:
            MYSQL_USER: cemenweb_webusua
            MYSQL_PASSWORD: wRmWxTGl1L4f
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: